// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using T_Shop.Infrastructure.Persistence;

#nullable disable

namespace T_Shop.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240507041137_add more default data")]
    partial class addmoredefaultdata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("T_Shop.Domain.Entity.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("table_category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("077639ee-e1bb-4949-8185-305b2916257f"),
                            Name = "Category1"
                        },
                        new
                        {
                            Id = new Guid("aac49e46-fe61-4529-9b46-7c5959b98150"),
                            Name = "Category2"
                        },
                        new
                        {
                            Id = new Guid("1d462595-6426-4fee-b441-c4211ffc006b"),
                            Name = "Category3"
                        },
                        new
                        {
                            Id = new Guid("c341573b-e057-4528-bc6a-c65599e0ca5f"),
                            Name = "Category4"
                        },
                        new
                        {
                            Id = new Guid("a264dd50-0232-4a61-b81b-3ec5c51eec81"),
                            Name = "Category5"
                        },
                        new
                        {
                            Id = new Guid("6bf5f935-efe4-4672-acca-65141d6eab42"),
                            Name = "Category6"
                        },
                        new
                        {
                            Id = new Guid("21ba1988-613f-4f87-83d5-7ac61537e102"),
                            Name = "Category7"
                        },
                        new
                        {
                            Id = new Guid("0c5390cc-3816-4576-94a8-6b7822046087"),
                            Name = "Category8"
                        },
                        new
                        {
                            Id = new Guid("9faf2697-b623-4849-ae76-5ddbe4b72eac"),
                            Name = "Category9"
                        },
                        new
                        {
                            Id = new Guid("5de9c997-158d-4560-beaa-d9c0c93fcbbc"),
                            Name = "Category10"
                        });
                });

            modelBuilder.Entity("T_Shop.Domain.Entity.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("FK_category_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("table_product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8407e4fb-614c-46ae-a932-a0a8b9e250ac"),
                            CategoryId = new Guid("6bf5f935-efe4-4672-acca-65141d6eab42"),
                            Description = "This is description for product1",
                            Name = "Product1"
                        },
                        new
                        {
                            Id = new Guid("943c99d0-cbc5-40d6-97b4-f8234b7d3fb4"),
                            CategoryId = new Guid("21ba1988-613f-4f87-83d5-7ac61537e102"),
                            Description = "This is description for product2",
                            Name = "Product2"
                        },
                        new
                        {
                            Id = new Guid("204dbde1-5e1e-404e-8cf4-2950351f8ac9"),
                            CategoryId = new Guid("1d462595-6426-4fee-b441-c4211ffc006b"),
                            Description = "This is description for product3",
                            Name = "Product3"
                        },
                        new
                        {
                            Id = new Guid("22efa751-881f-4b82-ba8b-1ea0fa91d0c5"),
                            CategoryId = new Guid("c341573b-e057-4528-bc6a-c65599e0ca5f"),
                            Description = "This is description for product4",
                            Name = "Product4"
                        },
                        new
                        {
                            Id = new Guid("cecf42f9-6dff-4669-8bda-0481b4b53315"),
                            CategoryId = new Guid("21ba1988-613f-4f87-83d5-7ac61537e102"),
                            Description = "This is description for product5",
                            Name = "Product5"
                        },
                        new
                        {
                            Id = new Guid("6aa34f7e-b29d-4311-92db-02dfa502ec2c"),
                            CategoryId = new Guid("21ba1988-613f-4f87-83d5-7ac61537e102"),
                            Description = "This is description for product6",
                            Name = "Product6"
                        },
                        new
                        {
                            Id = new Guid("206463da-3dfe-4b27-9def-88c92c0f69aa"),
                            CategoryId = new Guid("a264dd50-0232-4a61-b81b-3ec5c51eec81"),
                            Description = "This is description for product7",
                            Name = "Product7"
                        },
                        new
                        {
                            Id = new Guid("ccc95d89-f814-4109-9e3d-fbf15a2d2b33"),
                            CategoryId = new Guid("c341573b-e057-4528-bc6a-c65599e0ca5f"),
                            Description = "This is description for product8",
                            Name = "Product8"
                        },
                        new
                        {
                            Id = new Guid("acac2545-72a2-497d-9e92-b40223c82299"),
                            CategoryId = new Guid("1d462595-6426-4fee-b441-c4211ffc006b"),
                            Description = "This is description for product9",
                            Name = "Product9"
                        },
                        new
                        {
                            Id = new Guid("c146640c-814e-456b-bdf9-b286833272de"),
                            CategoryId = new Guid("c341573b-e057-4528-bc6a-c65599e0ca5f"),
                            Description = "This is description for product10",
                            Name = "Product10"
                        },
                        new
                        {
                            Id = new Guid("da6a21a8-884a-48b6-aa4f-aad33c6b5ea0"),
                            CategoryId = new Guid("1d462595-6426-4fee-b441-c4211ffc006b"),
                            Description = "This is description for product11",
                            Name = "Product11"
                        },
                        new
                        {
                            Id = new Guid("38f65a99-b877-4d27-9708-e1042bcaf4a8"),
                            CategoryId = new Guid("21ba1988-613f-4f87-83d5-7ac61537e102"),
                            Description = "This is description for product12",
                            Name = "Product12"
                        },
                        new
                        {
                            Id = new Guid("dace0360-2fb7-43f0-96e4-2a742c556a79"),
                            CategoryId = new Guid("c341573b-e057-4528-bc6a-c65599e0ca5f"),
                            Description = "This is description for product13",
                            Name = "Product13"
                        },
                        new
                        {
                            Id = new Guid("c78ce2fb-ce64-4d27-a8f4-7c8213362399"),
                            CategoryId = new Guid("21ba1988-613f-4f87-83d5-7ac61537e102"),
                            Description = "This is description for product14",
                            Name = "Product14"
                        },
                        new
                        {
                            Id = new Guid("fa7d520e-ebc0-4ad6-83d4-d99763f65e49"),
                            CategoryId = new Guid("6bf5f935-efe4-4672-acca-65141d6eab42"),
                            Description = "This is description for product15",
                            Name = "Product15"
                        },
                        new
                        {
                            Id = new Guid("4a072176-1904-4fe8-add2-c9f4a6cf66ca"),
                            CategoryId = new Guid("c341573b-e057-4528-bc6a-c65599e0ca5f"),
                            Description = "This is description for product16",
                            Name = "Product16"
                        },
                        new
                        {
                            Id = new Guid("f55932c1-7f16-4f45-9be2-4bb9690b18b7"),
                            CategoryId = new Guid("9faf2697-b623-4849-ae76-5ddbe4b72eac"),
                            Description = "This is description for product17",
                            Name = "Product17"
                        },
                        new
                        {
                            Id = new Guid("68926ca6-cef9-4d5e-997d-3e679f1124d6"),
                            CategoryId = new Guid("5de9c997-158d-4560-beaa-d9c0c93fcbbc"),
                            Description = "This is description for product18",
                            Name = "Product18"
                        },
                        new
                        {
                            Id = new Guid("d72ea2e6-a71c-4fec-99fe-f61b84a8af93"),
                            CategoryId = new Guid("6bf5f935-efe4-4672-acca-65141d6eab42"),
                            Description = "This is description for product19",
                            Name = "Product19"
                        },
                        new
                        {
                            Id = new Guid("cde59207-766f-437f-84fc-9a4decf5552b"),
                            CategoryId = new Guid("9faf2697-b623-4849-ae76-5ddbe4b72eac"),
                            Description = "This is description for product20",
                            Name = "Product20"
                        },
                        new
                        {
                            Id = new Guid("b86b6488-378e-48d7-8c2f-61beb30552d8"),
                            CategoryId = new Guid("aac49e46-fe61-4529-9b46-7c5959b98150"),
                            Description = "This is description for product21",
                            Name = "Product21"
                        },
                        new
                        {
                            Id = new Guid("76fbfd4e-00bf-480f-97e5-ea3e311ceed8"),
                            CategoryId = new Guid("c341573b-e057-4528-bc6a-c65599e0ca5f"),
                            Description = "This is description for product22",
                            Name = "Product22"
                        },
                        new
                        {
                            Id = new Guid("264858ac-c654-452b-9491-a3e71baea32e"),
                            CategoryId = new Guid("c341573b-e057-4528-bc6a-c65599e0ca5f"),
                            Description = "This is description for product23",
                            Name = "Product23"
                        },
                        new
                        {
                            Id = new Guid("525a8b9a-58ad-41fd-8dbf-619750774052"),
                            CategoryId = new Guid("c341573b-e057-4528-bc6a-c65599e0ca5f"),
                            Description = "This is description for product24",
                            Name = "Product24"
                        },
                        new
                        {
                            Id = new Guid("d4893841-a899-4923-b095-979ae8b77735"),
                            CategoryId = new Guid("5de9c997-158d-4560-beaa-d9c0c93fcbbc"),
                            Description = "This is description for product25",
                            Name = "Product25"
                        },
                        new
                        {
                            Id = new Guid("26b9e1ed-502f-45b1-bf2d-f4906fd64969"),
                            CategoryId = new Guid("1d462595-6426-4fee-b441-c4211ffc006b"),
                            Description = "This is description for product26",
                            Name = "Product26"
                        },
                        new
                        {
                            Id = new Guid("235a207c-79cc-4e3d-8c18-724c677b4d10"),
                            CategoryId = new Guid("0c5390cc-3816-4576-94a8-6b7822046087"),
                            Description = "This is description for product27",
                            Name = "Product27"
                        },
                        new
                        {
                            Id = new Guid("5bc21063-d5e4-4352-874d-1b30c2987e65"),
                            CategoryId = new Guid("1d462595-6426-4fee-b441-c4211ffc006b"),
                            Description = "This is description for product28",
                            Name = "Product28"
                        },
                        new
                        {
                            Id = new Guid("97fdca4f-d6c1-44aa-934d-4cc6a01012c2"),
                            CategoryId = new Guid("5de9c997-158d-4560-beaa-d9c0c93fcbbc"),
                            Description = "This is description for product29",
                            Name = "Product29"
                        },
                        new
                        {
                            Id = new Guid("bd1f389d-f2ce-438a-948b-725c9f19e0e4"),
                            CategoryId = new Guid("9faf2697-b623-4849-ae76-5ddbe4b72eac"),
                            Description = "This is description for product30",
                            Name = "Product30"
                        },
                        new
                        {
                            Id = new Guid("613db9dd-ca44-4502-9e40-75f5ee12120f"),
                            CategoryId = new Guid("c341573b-e057-4528-bc6a-c65599e0ca5f"),
                            Description = "This is description for product31",
                            Name = "Product31"
                        },
                        new
                        {
                            Id = new Guid("bf114e9a-a8cc-4b75-86a0-ba2b4bda27b1"),
                            CategoryId = new Guid("9faf2697-b623-4849-ae76-5ddbe4b72eac"),
                            Description = "This is description for product32",
                            Name = "Product32"
                        },
                        new
                        {
                            Id = new Guid("046e9684-ee35-4ed0-a860-48f834bf5332"),
                            CategoryId = new Guid("0c5390cc-3816-4576-94a8-6b7822046087"),
                            Description = "This is description for product33",
                            Name = "Product33"
                        },
                        new
                        {
                            Id = new Guid("812c0465-e278-4a33-a1af-773ebf71e430"),
                            CategoryId = new Guid("0c5390cc-3816-4576-94a8-6b7822046087"),
                            Description = "This is description for product34",
                            Name = "Product34"
                        },
                        new
                        {
                            Id = new Guid("32834c4b-2c41-452d-a532-8a4c0719737e"),
                            CategoryId = new Guid("0c5390cc-3816-4576-94a8-6b7822046087"),
                            Description = "This is description for product35",
                            Name = "Product35"
                        },
                        new
                        {
                            Id = new Guid("0e8cf19a-6432-482b-bd68-1bc088a83d05"),
                            CategoryId = new Guid("21ba1988-613f-4f87-83d5-7ac61537e102"),
                            Description = "This is description for product36",
                            Name = "Product36"
                        },
                        new
                        {
                            Id = new Guid("0c60e000-7de5-4291-89da-7c79fcf21427"),
                            CategoryId = new Guid("c341573b-e057-4528-bc6a-c65599e0ca5f"),
                            Description = "This is description for product37",
                            Name = "Product37"
                        },
                        new
                        {
                            Id = new Guid("5a75391b-9145-482a-89e1-976fdd97ef63"),
                            CategoryId = new Guid("aac49e46-fe61-4529-9b46-7c5959b98150"),
                            Description = "This is description for product38",
                            Name = "Product38"
                        },
                        new
                        {
                            Id = new Guid("ab12932a-84bb-4f33-893a-ca76d3475a6e"),
                            CategoryId = new Guid("6bf5f935-efe4-4672-acca-65141d6eab42"),
                            Description = "This is description for product39",
                            Name = "Product39"
                        },
                        new
                        {
                            Id = new Guid("a2e08dee-1059-4658-a06f-aebdda4ff89f"),
                            CategoryId = new Guid("c341573b-e057-4528-bc6a-c65599e0ca5f"),
                            Description = "This is description for product40",
                            Name = "Product40"
                        },
                        new
                        {
                            Id = new Guid("94dd4d20-b288-4643-a321-cad7c9496289"),
                            CategoryId = new Guid("9faf2697-b623-4849-ae76-5ddbe4b72eac"),
                            Description = "This is description for product41",
                            Name = "Product41"
                        },
                        new
                        {
                            Id = new Guid("e8ba087a-3cd9-46a3-8e5d-536da6185020"),
                            CategoryId = new Guid("0c5390cc-3816-4576-94a8-6b7822046087"),
                            Description = "This is description for product42",
                            Name = "Product42"
                        },
                        new
                        {
                            Id = new Guid("36365cdc-3d45-4b3d-a712-65d9d43159d8"),
                            CategoryId = new Guid("0c5390cc-3816-4576-94a8-6b7822046087"),
                            Description = "This is description for product43",
                            Name = "Product43"
                        },
                        new
                        {
                            Id = new Guid("5324cedc-de16-4527-9ac4-7ced93ae3f9f"),
                            CategoryId = new Guid("1d462595-6426-4fee-b441-c4211ffc006b"),
                            Description = "This is description for product44",
                            Name = "Product44"
                        },
                        new
                        {
                            Id = new Guid("d8b7b4ea-64aa-4c28-9c12-4bcc47ccdd3c"),
                            CategoryId = new Guid("aac49e46-fe61-4529-9b46-7c5959b98150"),
                            Description = "This is description for product45",
                            Name = "Product45"
                        },
                        new
                        {
                            Id = new Guid("15c8e0f8-f168-4624-aac7-2398440119a3"),
                            CategoryId = new Guid("a264dd50-0232-4a61-b81b-3ec5c51eec81"),
                            Description = "This is description for product46",
                            Name = "Product46"
                        },
                        new
                        {
                            Id = new Guid("29d1bae2-a396-4cc8-805c-66dc07a72129"),
                            CategoryId = new Guid("c341573b-e057-4528-bc6a-c65599e0ca5f"),
                            Description = "This is description for product47",
                            Name = "Product47"
                        },
                        new
                        {
                            Id = new Guid("24e18eba-d78c-484f-a29f-406d5c445b65"),
                            CategoryId = new Guid("c341573b-e057-4528-bc6a-c65599e0ca5f"),
                            Description = "This is description for product48",
                            Name = "Product48"
                        },
                        new
                        {
                            Id = new Guid("944aa228-4774-48fb-95ae-2ca567b0617a"),
                            CategoryId = new Guid("6bf5f935-efe4-4672-acca-65141d6eab42"),
                            Description = "This is description for product49",
                            Name = "Product49"
                        },
                        new
                        {
                            Id = new Guid("7611f5fa-48a2-400e-aee8-0c18d98ef601"),
                            CategoryId = new Guid("0c5390cc-3816-4576-94a8-6b7822046087"),
                            Description = "This is description for product50",
                            Name = "Product50"
                        });
                });

            modelBuilder.Entity("T_Shop.Domain.Entity.Product", b =>
                {
                    b.HasOne("T_Shop.Domain.Entity.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("T_Shop.Domain.Entity.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
